# Generated by Django 3.2.25 on 2025-10-07 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_department_announcement_course_enrollment_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='target_role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('all', 'All')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
